import { Inter } from "next/font/google";
import "./globals.css";
import { StackProvider } from "@stackframe/stack";
import { stackServerApp } from "../stack";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">
        <StackProvider app={stackServerApp}>
        <body className={inter.className}>{children}</body>
        </StackProvider>
      </html>
  );
}